"""Unit tests for scripts/sync_requirements.py.

Loads the script via importlib.util (no scripts package import — scripts/ has
no __init__.py so `from scripts.sync_requirements import ...` would fail under pytest).
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SPEC = importlib.util.spec_from_file_location(
    "sync_requirements",
    Path(__file__).parent.parent / "scripts" / "sync_requirements.py",
)
sync_requirements = importlib.util.module_from_spec(_SPEC)  # type: ignore[arg-type]
_SPEC.loader.exec_module(sync_requirements)  # type: ignore[union-attr]


@pytest.fixture
def fake_env(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """Redirect REQUIREMENTS_FILE to tmp_path and stub pixi + pyproject lookups."""
    req = tmp_path / "requirements.txt"
    monkeypatch.setattr(sync_requirements, "REQUIREMENTS_FILE", req)
    monkeypatch.setattr(
        sync_requirements,
        "_runtime_deps",
        lambda: {"fastapi": "", "uvicorn": "[standard]"},
    )
    monkeypatch.setattr(
        sync_requirements,
        "_pixi_versions",
        lambda: {"fastapi": "1.2.3", "uvicorn": "0.9.0"},
    )
    return req


class TestGenerate:
    def test_creates_file(self, fake_env: Path) -> None:
        sync_requirements.generate()
        assert fake_env.exists()

    def test_header_present(self, fake_env: Path) -> None:
        sync_requirements.generate()
        text = fake_env.read_text()
        assert "Auto-generated by scripts/sync_requirements.py" in text
        assert "do not edit by hand" in text

    def test_pins_exact_versions(self, fake_env: Path) -> None:
        sync_requirements.generate()
        text = fake_env.read_text()
        assert "fastapi==1.2.3" in text
        assert "uvicorn[standard]==0.9.0" in text

    def test_sorted_alphabetically(self, fake_env: Path) -> None:
        sync_requirements.generate()
        pin_lines = [
            ln for ln in fake_env.read_text().splitlines() if "==" in ln and not ln.startswith("#")
        ]
        assert pin_lines == sorted(pin_lines)


class TestCheck:
    def test_in_sync_exits_ok(self, fake_env: Path, capsys: pytest.CaptureFixture[str]) -> None:
        sync_requirements.generate()
        sync_requirements.check()  # must not raise SystemExit
        assert "OK" in capsys.readouterr().out

    def test_detects_drift(self, fake_env: Path) -> None:
        sync_requirements.generate()
        fake_env.write_text(fake_env.read_text().replace("1.2.3", "9.9.9"))
        with pytest.raises(SystemExit) as exc_info:
            sync_requirements.check()
        assert exc_info.value.code != 0

    def test_missing_file_exits_nonzero(self, fake_env: Path) -> None:
        assert not fake_env.exists()
        with pytest.raises(SystemExit) as exc_info:
            sync_requirements.check()
        assert exc_info.value.code != 0

    def test_missing_file_error_message(self, fake_env: Path) -> None:
        with pytest.raises(SystemExit) as exc_info:
            sync_requirements.check()
        # sys.exit(string) stores the message in exc_info.value.code
        assert "does not exist" in str(exc_info.value.code)

    def test_drift_error_mentions_sync_reqs(self, fake_env: Path) -> None:
        sync_requirements.generate()
        fake_env.write_text(fake_env.read_text().replace("1.2.3", "0.0.1"))
        with pytest.raises(SystemExit) as exc_info:
            sync_requirements.check()
        assert "sync-reqs" in str(exc_info.value.code)


class TestHelpers:
    def test_canon_normalizes_hyphens_underscores_dots(self) -> None:
        assert sync_requirements._canon("my_pkg") == "my-pkg"
        assert sync_requirements._canon("My.Pkg") == "my-pkg"
        assert sync_requirements._canon("my--pkg") == "my-pkg"

    def test_canon_lowercases(self) -> None:
        assert sync_requirements._canon("FastAPI") == "fastapi"

    def test_runtime_deps_missing_dep_in_pixi(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        req = tmp_path / "requirements.txt"
        monkeypatch.setattr(sync_requirements, "REQUIREMENTS_FILE", req)
        monkeypatch.setattr(
            sync_requirements,
            "_runtime_deps",
            lambda: {"fastapi": "", "missing-pkg": ""},
        )
        monkeypatch.setattr(
            sync_requirements,
            "_pixi_versions",
            lambda: {"fastapi": "1.0.0"},  # missing-pkg absent
        )
        with pytest.raises(SystemExit) as exc_info:
            sync_requirements._build_lines()
        assert exc_info.value.code != 0
        assert "missing-pkg" in str(exc_info.value.code)
