#!/usr/bin/env python3
"""CI guardrail: verify dependency version ranges are consistent.

Two checks are performed:

1. Every entry in pyproject.toml ``[project.dependencies]`` has a ``<`` upper
   bound. Without an upper bound, ``pip install .`` may pull a breaking major
   release.

2. Every production dependency must appear in BOTH pyproject.toml
   ``[project.dependencies]`` AND pixi.toml ``[pypi-dependencies]`` with the
   same version range (bidirectional parity). This prevents drift where one
   file is updated but not the other (see #497, follow-up from #338).

The script exits non-zero on any failure, printing the offending entries with
the file each one came from so reviewers can pinpoint the drift.

``--fix`` rewrites pixi.toml ``[pypi-dependencies]`` version ranges to match
pyproject.toml ``[project.dependencies]`` (comment-preserving, line-based).
This exists because Dependabot's ``pip`` ecosystem can only edit
pyproject.toml — the derived pixi.toml ranges and pixi.lock are regenerated by
the dependabot-pixi-sync producer/writer workflows (see #497).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parent.parent
PYPROJECT = ROOT / "pyproject.toml"
PIXI = ROOT / "pixi.toml"

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore[import-not-found,no-redef,unused-ignore]
        except ImportError:
            print("ERROR: tomli is required on Python < 3.11 (pip install tomli)", file=sys.stderr)
            sys.exit(1)


# Project package itself in pixi (path-installed); has no version range to compare.
SELF_PACKAGE = "hermes"

# Strip any PEP 508 extras and environment markers from a pyproject entry.
# Examples handled:
#   "uvicorn[standard]>=0.46.0,<1"     -> ("uvicorn", ">=0.46.0,<1")
#   "fastapi>=0.115,<1"                -> ("fastapi", ">=0.115,<1")
#   "httpx>=0.27,<1 ; python_version<'4'\" -> ("httpx", ">=0.27,<1")
_NAME_RE = re.compile(r"^\s*([A-Za-z0-9_.\-]+)(?:\[[^\]]*\])?\s*(.*?)\s*$")

# Matches a pixi.toml [pypi-dependencies] entry. Two shapes are handled:
#   name = ">=1.2,<2"
#   name = {version = ">=1.2,<2", extras = ["standard"]}
_PIXI_STRING_ENTRY_RE = re.compile(
    r'^(\s*[A-Za-z0-9_.\-]+\s*=\s*)"([^"]*)"(.*)$'
)
_PIXI_TABLE_ENTRY_RE = re.compile(
    r'^(\s*[A-Za-z0-9_.\-]+\s*=\s*\{[^}]*version\s*=\s*)"([^"]*)"(.*)$'
)


def _canon(name: str) -> str:
    """PEP 503 canonical name (lowercase, runs of [-_.] collapsed to '-')."""
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_pyproject(deps: list[str]) -> dict[str, str]:
    """Return {canonical_name: version_spec} from PEP 508 entries."""
    out: dict[str, str] = {}
    for entry in deps:
        # Drop environment marker, if any.
        head = entry.split(";", 1)[0]
        m = _NAME_RE.match(head)
        if not m:
            raise SystemExit(f"pyproject.toml: cannot parse dependency entry {entry!r}")
        name, spec = m.group(1), m.group(2).strip()
        out[_canon(name)] = spec
    return out


def parse_pixi(table: dict[str, Any]) -> dict[str, str]:
    """Return {canonical_name: version_spec} from a pixi pypi-dependencies table.

    Pixi entries can be either bare strings (``"fastapi" = ">=0.115,<1"``) or
    inline tables (``{ version = ">=0.46.0,<1", extras = ["standard"] }``).
    The self-install entry (``{ path = ".", editable = true }``) is skipped
    since it carries no version to compare.
    """
    out: dict[str, str] = {}
    for name, value in table.items():
        cname = _canon(name)
        if cname == SELF_PACKAGE:
            continue
        if isinstance(value, str):
            out[cname] = value.strip()
        elif isinstance(value, dict):
            if "path" in value or "git" in value or "url" in value:
                # Local / VCS install — no PyPI version range to compare.
                continue
            ver = value.get("version")
            if not isinstance(ver, str):
                raise SystemExit(
                    f"pixi.toml: entry {name!r} has no 'version' string under [pypi-dependencies]"
                )
            out[cname] = ver.strip()
        else:
            raise SystemExit(
                f"pixi.toml: unexpected value type for {name!r}: {type(value).__name__}"
            )
    return out


def _load(path: Path) -> dict[str, Any]:
    with path.open("rb") as fh:
        data: dict[str, Any] = tomllib.load(fh)
    return data


def check_upper_bounds(deps: list[str]) -> list[str]:
    return [f"  {entry!r} — missing '<' upper bound" for entry in deps if "<" not in entry]


def check_parity(py: dict[str, str], pixi: dict[str, str]) -> list[str]:
    """Return human-readable failure lines for any drift between the two maps.

    The check is bidirectional: a dependency must appear in BOTH files with
    the same version range. A name present in only one file is a drift case
    (the maintainer updated one file and forgot the other — see #497).
    """
    failures: list[str] = []
    for name, pixi_spec in sorted(pixi.items()):
        py_spec = py.get(name)
        if py_spec is None:
            failures.append(
                f"  {name}: declared in pixi.toml ({pixi_spec!r}) but missing from "
                f"pyproject.toml [project.dependencies]"
            )
            continue
        if py_spec != pixi_spec:
            failures.append(
                f"  {name}: pyproject.toml has {py_spec!r}, pixi.toml has {pixi_spec!r}"
            )
    for name, py_spec in sorted(py.items()):
        if name == SELF_PACKAGE:
            continue
        if name not in pixi:
            failures.append(
                f"  {name}: declared in pyproject.toml ({py_spec!r}) but missing from "
                f"pixi.toml [pypi-dependencies]"
            )
    return failures


def _sync_pixi_from_pyproject(py: dict[str, str], pixi: dict[str, str]) -> int:
    """Rewrite pixi.toml [pypi-dependencies] version ranges from pyproject.toml.

    Comment-preserving line-based edit. Only entries that exist in BOTH files
    with a drifted range are rewritten; entries unique to one file are left
    untouched (the parity check reports them, but --fix must not invent or
    delete dependencies). Returns the number of lines rewritten.
    """
    pixi_lines = PIXI.read_text(encoding="utf-8").splitlines(keepends=True)
    changed = 0
    in_pypi = False
    for i, line in enumerate(pixi_lines):
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            in_pypi = stripped == "[pypi-dependencies]"
            continue
        if not in_pypi or not stripped or stripped.startswith("#"):
            continue
        # Match either the bare-string or inline-table pixi entry shape.
        sm = _PIXI_STRING_ENTRY_RE.match(line)
        tm = None if sm else _PIXI_TABLE_ENTRY_RE.match(line)
        m = sm or tm
        if not m:
            continue
        prefix, old_spec, suffix = m.group(1), m.group(2), m.group(3)
        name = re.match(r"\s*([A-Za-z0-9_.\-]+)", prefix)
        if not name:
            continue
        cname = _canon(name.group(1))
        new_spec = py.get(cname)
        if new_spec is None or new_spec == old_spec:
            continue
        # For table entries the closing part (extras, etc.) is already in suffix.
        # Preserve the trailing newline: the regex match ends before it, so a
        # naive rebuild would splice the next line onto this one.
        ends_newline = line.endswith("\n")
        pixi_lines[i] = f'{prefix}"{new_spec}"{suffix}'
        if ends_newline and not pixi_lines[i].endswith("\n"):
            pixi_lines[i] += "\n"
        changed += 1
    if changed:
        PIXI.write_text("".join(pixi_lines), encoding="utf-8")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fix",
        action="store_true",
        help="rewrite pixi.toml [pypi-dependencies] ranges from pyproject.toml",
    )
    # Bare main() calls from tests must not consume sys.argv (pytest args).
    args = parser.parse_args(argv if argv is not None else [])

    py_data = _load(PYPROJECT)
    pixi_data = _load(PIXI)

    py_deps_raw: list[str] | None = py_data.get("project", {}).get("dependencies")
    if not py_deps_raw:
        print(
            "FAIL: [project.dependencies] is missing or empty in pyproject.toml.\n"
            "      Add version-bounded runtime dependencies so 'pip install .' is reproducible.",
            file=sys.stderr,
        )
        return 1

    bound_failures = check_upper_bounds(py_deps_raw)
    if bound_failures:
        print(
            "FAIL: The following [project.dependencies] entries have no upper bound (<).\n"
            "      Without an upper bound, 'pip install .' may pull breaking major versions.\n",
            file=sys.stderr,
        )
        for line in bound_failures:
            print(line, file=sys.stderr)
        print('\nFix by adding an upper bound, e.g.:\n  "some-package>=1.2,<2"', file=sys.stderr)
        return 1

    py_deps = parse_pyproject(py_deps_raw)
    pixi_table = pixi_data.get("pypi-dependencies", {})
    pixi_deps = parse_pixi(pixi_table)

    if args.fix:
        changed = _sync_pixi_from_pyproject(py_deps, pixi_deps)
        if changed:
            print(f"FIXED: rewrote {changed} pixi.toml [pypi-dependencies] range(s) to match pyproject.toml.")
        else:
            print("FIXED: no pixi.toml [pypi-dependencies] drift detected.")
        # Re-load and re-verify so --fix is self-checking.
        pixi_data = _load(PIXI)
        pixi_deps = parse_pixi(pixi_data.get("pypi-dependencies", {}))

    parity_failures = check_parity(py_deps, pixi_deps)
    if parity_failures:
        print(
            "FAIL: pixi.toml [pypi-dependencies] and pyproject.toml [project.dependencies] "
            "have drifted.\n"
            "      Production dependency version ranges must be identical in both files.\n",
            file=sys.stderr,
        )
        for line in parity_failures:
            print(line, file=sys.stderr)
        print(
            "\nFix by updating one file so both declare the same version range.",
            file=sys.stderr,
        )
        return 1

    print(
        f"OK: {len(py_deps_raw)} dependencies in [project.dependencies], all upper-bounded "
        f"and consistent with pixi.toml [pypi-dependencies] ({len(pixi_deps)} prod entries)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
