#!/usr/bin/env python3
"""Generate or validate requirements.txt from pixi.lock via `pixi list --json`.

Usage:
    python scripts/sync_requirements.py           # generate requirements.txt
    python scripts/sync_requirements.py --check   # exit 1 if out of sync
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
REQUIREMENTS_FILE = REPO_ROOT / "requirements.txt"
PIXI_TOML = REPO_ROOT / "pixi.toml"

HEADER = (
    "# Auto-generated by scripts/sync_requirements.py — do not edit by hand.\n"
    "# Source: pixi list --json (reads pixi.lock)\n"
    "# Regenerate: python scripts/sync_requirements.py\n"
)

# Packages that need extras appended in requirements.txt
_EXTRAS: dict[str, str] = {
    "uvicorn": "[standard]",
}

# Canonical names as they appear in pixi.toml [pypi-dependencies]
_RUNTIME_DEPS: set[str] = {
    "fastapi",
    "uvicorn",
    "nats-py",
    "pydantic",
    "pydantic-settings",
    "httpx",
    "slowapi",
    "limits",
    "prometheus-client",
}


def _normalize(name: str) -> str:
    """Normalize a package name to lowercase with hyphens."""
    return name.lower().replace("_", "-")


def _pixi_versions() -> dict[str, str]:
    """Return {normalized-name: version} for all runtime deps from pixi.lock."""
    result = subprocess.run(
        ["pixi", "list", "--json"],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    packages: list[dict] = json.loads(result.stdout)
    versions: dict[str, str] = {}
    for pkg in packages:
        if pkg.get("kind") != "pypi":
            continue
        norm = _normalize(pkg["name"])
        if norm in _RUNTIME_DEPS:
            versions[norm] = pkg["version"]
    missing = _RUNTIME_DEPS - versions.keys()
    if missing:
        sys.exit(f"ERROR: packages not found in pixi list output: {sorted(missing)}")
    return versions


def _build_lines(versions: dict[str, str]) -> list[str]:
    """Build sorted requirement lines from version mapping."""
    lines: list[str] = []
    for name in sorted(versions):
        extras = _EXTRAS.get(name, "")
        lines.append(f"{name}{extras}=={versions[name]}")
    return lines


def generate() -> None:
    """Write requirements.txt with exact pins from pixi.lock."""
    versions = _pixi_versions()
    lines = _build_lines(versions)
    content = HEADER + "\n".join(lines) + "\n"
    REQUIREMENTS_FILE.write_text(content)
    print(f"Written {REQUIREMENTS_FILE.relative_to(REPO_ROOT)} ({len(lines)} packages)")


def check() -> None:
    """Exit non-zero if requirements.txt does not match pixi.lock."""
    if not REQUIREMENTS_FILE.exists():
        sys.exit(f"ERROR: {REQUIREMENTS_FILE} does not exist. Run: python scripts/sync_requirements.py")

    versions = _pixi_versions()
    expected_lines = _build_lines(versions)
    expected = HEADER + "\n".join(expected_lines) + "\n"

    actual = REQUIREMENTS_FILE.read_text()
    if actual == expected:
        print("OK: requirements.txt is in sync with pixi.lock")
        return

    # Report which lines differ
    actual_pins = {
        line.split("==")[0].split("[")[0]: line
        for line in actual.splitlines()
        if "==" in line and not line.startswith("#")
    }
    expected_pins = {
        line.split("==")[0].split("[")[0]: line
        for line in expected_lines
    }
    diffs: list[str] = []
    for name, exp_line in expected_pins.items():
        act_line = actual_pins.get(name)
        if act_line != exp_line:
            diffs.append(f"  {name}: expected '{exp_line}', got '{act_line or '(missing)'}'")
    for name in set(actual_pins) - set(expected_pins):
        diffs.append(f"  {name}: unexpected entry '{actual_pins[name]}'")

    sys.exit(
        "ERROR: requirements.txt is out of sync with pixi.lock:\n"
        + "\n".join(diffs)
        + "\nRun: python scripts/sync_requirements.py"
    )


def main() -> None:
    if "--check" in sys.argv:
        check()
    else:
        generate()


if __name__ == "__main__":
    main()
